"""Initial schema

Revision ID: ed0460382079
Revises:
Create Date: 2026-06-12 07:55:09.306068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'ed0460382079'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create pgvector extension (PostgreSQL only, no-op for SQLite)
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'ANONYMOUS', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', app.db.types.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_chat_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CONFLUENCE', 'JIRA', 'GITHUB', 'ONBOARDING', name='source_type'), nullable=False),
    sa.Column('config', app.db.types.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SUCCESS', 'FAILED', name='sync_status'), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_sources_created_by', 'data_sources', ['created_by'], unique=False)
    op.create_index('ix_data_sources_is_active', 'data_sources', ['is_active'], unique=False)
    op.create_index('ix_data_sources_sync_status', 'data_sources', ['sync_status'], unique=False)
    op.create_index('ix_data_sources_type', 'data_sources', ['type'], unique=False)
    op.create_table('documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('source_id', app.db.types.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata', app.db.types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_external_id', 'documents', ['external_id'], unique=False)
    op.create_index('ix_documents_is_deleted', 'documents', ['is_deleted'], unique=False)
    op.create_index('ix_documents_source_id', 'documents', ['source_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sources', app.db.types.JSON(), nullable=True),
    sa.Column('feedback', app.db.types.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('source_id', app.db.types.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SYNCING', 'SUCCESS', 'FAILED', name='sync_status'), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_added', sa.Integer(), nullable=False),
    sa.Column('documents_updated', sa.Integer(), nullable=False),
    sa.Column('documents_deleted', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_logs_source_id', 'sync_logs', ['source_id'], unique=False)
    op.create_index('ix_sync_logs_started_at', 'sync_logs', ['started_at'], unique=False)
    op.create_index('ix_sync_logs_status', 'sync_logs', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('document_id', app.db.types.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('metadata', app.db.types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_chunk_index', 'document_chunks', ['chunk_index'], unique=False)
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)

    # Create IVFFlat index for vector similarity search (PostgreSQL only)
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        # Create IVFFlat index for fast approximate nearest neighbor search
        # lists=100 is a good starting point for datasets with thousands of vectors
        op.execute(
            'CREATE INDEX ix_document_chunks_embedding_vector '
            'ON document_chunks USING ivfflat (embedding vector_cosine_ops) '
            'WITH (lists = 100)'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop IVFFlat index (PostgreSQL only)
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute('DROP INDEX IF EXISTS ix_document_chunks_embedding_vector')

    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_chunk_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_sync_logs_status', table_name='sync_logs')
    op.drop_index('ix_sync_logs_started_at', table_name='sync_logs')
    op.drop_index('ix_sync_logs_source_id', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('ix_messages_session_id', table_name='messages')
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_documents_source_id', table_name='documents')
    op.drop_index('ix_documents_is_deleted', table_name='documents')
    op.drop_index('ix_documents_external_id', table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_data_sources_type', table_name='data_sources')
    op.drop_index('ix_data_sources_sync_status', table_name='data_sources')
    op.drop_index('ix_data_sources_is_active', table_name='data_sources')
    op.drop_index('ix_data_sources_created_by', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_created_at', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')

    # Drop pgvector extension (PostgreSQL only)
    # Note: We don't drop the extension by default as it might be used by other databases
    # If you want to drop it, uncomment the following lines:
    # connection = op.get_bind()
    # if connection.dialect.name == 'postgresql':
    #     op.execute('DROP EXTENSION IF EXISTS vector')

    # ### end Alembic commands ###
